### PR TITLE
Fix handling of uncaught errors from chain.js. Fixes #344

### LINKED ISSUE #344: Unhandled exceptions in the blockchain process aren't passed back to the main process
In bugs like #126 the chain process crashes, but the main process isn't aware.

My theory is that this is a race condition around startup and termination of the chain process.

On start of the chain process it immediately begins initialization (I think). After the process starts we wire up the IPC event handlers, but before they're set up the process crashes.

Similarly, on an unhandled exception/rejection an IPC message is sent, and then the chain process exits. If the child process end event is handled before the IPC message event, then the error won't have been seen by the parent process prior to displaying the BugModal.

### PR DESCRIPTION
**Pull request by benjamincburns**
See #344 for more info

### CODE REVIEW

File: src/Components/Title/TitleScreen.js [hunk 1]
```diff
@@ -39,21 +40,26 @@ class TitleScreen extends Component {
...
+            </strong>
+            <div className="GanacheVersion">
+              v{this.state.version}
+            </div>
+          </h4>
+        </div>
+        <OnlyIf test={this.props.core.systemError != null}>
+          <BugModal systemError={this.props.core.systemError} logs={this.props.logs} />
+        </OnlyIf>
       </div>
```
Comment (benjamincburns) [inline src/Components/Title/TitleScreen.js]: If I don't add the extra div here, the styling from TitleScreen applies.

My thinking was maybe I should clear the styling in BugModal and reapply it so that it's explicit, but that makes maintenance a bit of a drag.
