### PR TITLE
Handle Startup Errors

### LINKED ISSUE #627: Handle `EACESS` Network Startup Error
PLATFORM: win32
GANACHE VERSION: 1.1.0

EXCEPTION:
```
Error: listen EACCES 127.0.0.1:8545
    at Object.exports._errnoException (util.js:1024:11)
    at exports._exceptionWithHostPort (util.js:1047:20)
    at Server.setupListenHandle [as _listen2] (net.js:1302:19)
    at listenInCluster (net.js:1367:12)
    at doListen (net.js:1493:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

APPLICATION LOG:
```
T+0ms: Starting server with initial configuration: {"hostname":"127.0.0.1","port":8545,"network_id":5777,"total_accounts":10,"unlocked_accounts":[],"vmErrorsOnRPCResponse":true}
```

### LINKED ISSUE #665: Handle `EADDRINUSE` Network Startup Error
Several users are experiencing the below error. This issue will serve as the main issue to address this error.

```
Error: listen EADDRINUSE <IP_ADDRESS>:<PORT>
```

## Potential Causes
- There is a possible bug in Ganache where if it restarts quickly, the port isn't unbound before restart.
- There is more than one instance of Ganache running; which is not supported currently
- There is another program using that port

## Mitigations/Work-arounds (aka how to fix the issue until we patch this)
- Stop all instances of Ganache, wait a minute, and then only start one instance of Ganache
- Change the interface and/or port in the `Settings` file as to prevent collisions from another program (be sure to restart Ganache after saving the `Settings` file):
  - MacOS: `~/Library/Application\ Support/Ganache/Settings`
  - Windows: `%APPDATA%\Ganache\Settings`
  - Linux: either `$XDG_CONFIG_HOME/Ganache/Settings` or `~/.config/Ganache/Settings`

## Description
As part of this issue, the following will be addressed:
- Determine why these errors are happening
- Address all causes for this same symptom (and open new issues if the cause is drastically different)
- Add a message instead of the error screen which will say that the IP/Port combo used is conflicting with another process, providing some generic instructions for trying to solve the problem before submitting an issue on GitHub
- Allow users to change settings rather than being stuck on an error page

Work will likely overlap with #666

### LINKED ISSUE #666: Handle `EADDRNOTAVAIL` Network Startup Error
Several users are experiencing the below error. This issue will serve as the main issue to address this error.

```
Error: listen EADDRNOTAVAIL <IP_ADDRESS>:<PORT>
```

## Potential Causes
- The hostname/IP address provided was typed incorrectly (i.e. `128.0.0.1` instead of the correct `127.0.0.1`)
- The hostname/IP address provided is a remote host (aka an IP address that doesn't belong to the computer that is running Ganache)
  - This typically happens when users try to point Ganache to another network (i.e. Ropsten, Rinkeby, Mainnet). Ganache currently doesn't support listening/passing-through other networks.
  - It could also happen if someone is trying to instantiate a blockchain that runs on another computer in the network. Ganache also doesn't support this kind of remote activity
- It appears that users notice this error after another error/crash. This makes me think the server process is not stopping cleanly, causing the port to not be unbound.

## Mitigations/Work-arounds (aka how to fix the issue until we patch this)
- Change the hostname/IP address in the `Settings` file as to prevent collisions from another program (be sure to restart Ganache after saving the `Settings` file):
  - MacOS: `~/Library/Application\ Support/Ganache/Settings`
  - Windows: `%APPDATA%\Ganache\Settings`.
  - Linux: either `$XDG_CONFIG_HOME/Ganache/Settings` or `~/.config/Ganache/Settings`.

## Description
As part of this issue, the following will be addressed:

- Determine why these errors are happening
- Address all causes for this same symptom (and open new issues if the cause is drastically different)
- Add a message instead of the error screen which will say that the IP/Port combo used is invalid (and why), providing some generic instructions for trying to solve the problem before submitting an issue on GitHub
- Allow users to change settings rather than being stuck on an error page

Work will likely overlap with #665

### LINKED ISSUE #710: Change Hostname Setting to Dropdown of Interface IPs
PLATFORM: darwin
GANACHE VERSION: 1.1.0

EXCEPTION:
```
Error: getaddrinfo ENOTFOUND localhost
    at errnoException (dns.js:50:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
```

APPLICATION LOG:
```
T+0ms: Starting server with initial configuration: {"hostname":"localhost","port":8545,"network_id":5777,"total_accounts":10,"unlocked_accounts":[],"vmErrorsOnRPCResponse":true}
```

### PR DESCRIPTION
**Pull request by seesemichaelj**
This PR fixes #627, fixes #665, fixes #666, and fixes #710. Known system errors will now go directly to the settings page, prompting the user to fix the issue on the appropriate setting.

This PR also implements some fixes to prevent the issues that caused #665 and #666:
- The `RELAUNCH` button on the system error modal dialog would keep a lingering chain process, causing the port to stay bound, causing #665 
- The `Hostname` field was a textbox, allowing arbitrary input. This field can only be IP addresses of the network interfaces. This PR changes this field to a dropdown of  those IP addresses, preventing #666

### CODE REVIEW

**Comment by seesemichaelj** [comment]
@benjamincburns FYI this PR only adds known system errors for EADDRINUSE, EADDRNOTAVAIL, and EACESS

File: src/Components/Config/ConfigScreen.js [hunk 1]
```diff
@@ -45,8 +60,15 @@ class ConfigScreen extends PureComponent {
     return _.isEqual(this.state.settings, this.props.settings) == false
   }
 
-  handleCancelPressed () {
-    hashHistory.pop();
+  handleCancelPressed = (e) => {
+    if (this.state.cancelIsRestart) {
```
Comment (benjamincburns) [inline src/Components/Config/ConfigScreen.js]: based on the usage here I'd suggest a name like `isStartupFailure` or something instead of `cancelIsRestart`

File: src/Components/Config/ConfigScreen.js [hunk 2]
```diff
@@ -72,6 +94,13 @@ class ConfigScreen extends PureComponent {
     const name = target.name
     let value = target.value
 
+    // the user is modifying this field; if there is an error, send an action to clear it
+    // the user has acknowledged the error by modifying the field
+    if (target.name in this.state.settings.validationErrors) {
+      getCurrentWebContents().send(Settings.CLEAR_SETTING_ERROR, target.name)
```
Comment (benjamincburns) [inline src/Components/Config/ConfigScreen.js]: It seems like this should be done by an action creator or saga

File: src/Elements/StyledSelect.js [hunk 3]
```diff
@@ -0,0 +1,21 @@
+import React, { Component } from 'react'
+
+class StyledSelect extends Component {
```
Comment (benjamincburns) [inline src/Elements/StyledSelect.js]: If the only thing this class adds is the default styling, then we might as well put the select style in the global style or in the stylesheet for the settings screen and use a normal `<select ...>`.

I think I recommended making it a component before - my thought was that the component should handle enumerating interfaces, and displaying those.

Comment (benjamincburns) [reply src/Elements/StyledSelect.js]: That said, I wonder if we should enumerate network interfaces in the renderer process. If we want to keep the web interface portable, it's probably best if this happens in the main process.

File: src/Reducers/Settings.js [hunk 4]
```diff
@@ -3,11 +3,30 @@ import * as Settings from '../Actions/Settings'
 const initialState = {}
 
 export default function (state = initialState, action) {
+  let nextState = JSON.parse(JSON.stringify(state))
```
Comment (benjamincburns) [inline src/Reducers/Settings.js]: `JSON.parse(JSON.stringify(...))` is pretty inefficient. We typically use `Object.assign({}, state, updatedState)` but `_.merge({}, state, updatedState)` is even better.

Comment (benjamincburns) [reply src/Reducers/Settings.js]: Also it's slightly more idiomatic if you do this inline w/ your case statements rather than create an object and then modify it in your cases. Up to you as to whether you want to change this, though.

File: src/Services/Settings.js [hunk 5]
```diff
@@ -6,6 +6,7 @@ const settings = require('electron-settings');
 const oldDefaultMnemonic =  "candy maple cake sugar pudding cream honey rich smooth crumble sweet treat";
 
 const initialSettings = {
+  validationErrors: {}, // of the format {SETTING_NAME (i.e. hosname would be server.hostname): "error text"}
```
Comment (benjamincburns) [inline src/Services/Settings.js]: Comment here is confusing. I don't know whether it should be `validationErrors: { server: { hostname: "error text" } }` or `validationErrors: { "server.hostname": "error text" }`.

Also isn't this state, not settings? Anything in the `initialSettings` blob should be expected to persist to the settings file. I don't think we want settings which define whether other settings are erroneous, do we? We have application logic for that.

File: src/main.js [hunk 6]
```diff
@@ -50,6 +54,18 @@ process.on('unhandledRejection', err => {
   }
 })
 
+var shouldQuit = app.makeSingleInstance(function(commandLine, workingDirectory) {
+  // Someone tried to run a second instance, we should focus our window.
+  if (mainWindow) {
```
Comment (benjamincburns) [inline src/main.js]: I thought we weren't going to add this feature, as it prevents running multiple instances on different ports?

Comment (benjamincburns) [reply src/main.js]: I'm okay to leave it in, I guess - but we'll need to make sure it's highlighted in the release notes. I'm sure it'll piss some users off.

Comment (seesemichaelj) [reply src/main.js]: We cannot currently run multiple instances on different ports because you currently can't run Ganache on multiple ports without a "hack" since both instances use the came config file.

The current "run on multiple ports" is due to a programming gap of checking things appropriately and I'd rather the application not fail for some users rather than let the hackers have their feature until we support it officially.

File: src/Components/AppShell/AppShell.js [hunk 7]
```diff
@@ -119,7 +119,7 @@ class AppShell extends Component {
             {this.props.children}
           </Scrollbars>
         </div>
-        <OnlyIf test={this.props.core.systemError != null}>
+        <OnlyIf test={this.props.core.systemError != null && this.props.core.showModal}>
```
[the remark this answers is not in the document]
Comment (seesemichaelj) [reply src/Components/AppShell/AppShell.js]: This is definitely future proofing here. Even if `showModal` currently is set to true only when there is a `systemError`, if for some reason `systemError` is not set in the future, then `BugModal` will have empty data. This is just being extra cautious, because why not?

I chose the name for `showModal` because `showBugModal` is awfully specific. It seems silly to have a booleans for `showBugModal`, `showUpdateModal`, `showNoticeModal`, `showXXXXModal`. Again just trying to be generic.

File: src/Actions/Settings.js [hunk 8]
```diff
@@ -1,7 +1,15 @@
 import { ipcRenderer } from 'electron'
+import { push } from 'react-router-redux'
 
 const prefix = 'SETTINGS'
 
+export const SHOW_CONFIG_SCREEN = `${prefix}/SHOW_CONFIG_SCREEN`
+export function showConfigScreen(tab) {
+  return function(dispatch, getState) {
+    dispatch(push("/config" + (tab ? ("/" + tab) : "")))
```
[the remark this answers is not in the document]
Comment (seesemichaelj) [reply src/Actions/Settings.js]: I didn't get a clear answer on this from you:
image
so I decided to maintain similar style that the rest of the repo had

File: src/Elements/StyledSelect.js (hunk 3 above)
Comment (seesemichaelj) [reply src/Elements/StyledSelect.js]: The `<select>` tag needs to be wrapped in a div that gets styled. The purpose of this component is to make it so I don't have to wrap every select in a div for styling purposes.

Comment (seesemichaelj) [reply src/Elements/StyledSelect.js]: To be generic, this component **should not** enumerate the interfaces. If you want, I can create a component `NetworkInterfacesSelect` that uses this component which just does the enumeration.

File: package.json [hunk 9]
```diff
@@ -196,6 +196,7 @@
     "find-process": "^1.1.0",
     "ganache-cli": "6.1.0",
     "lodash": "^3.10.1",
+    "lodash.padstart": "^4.6.1",
```
[the remark this answers is not in the document]
Comment (seesemichaelj) [reply package.json]: Nevermind; I'm just going to do it in this PR for simplicity.

File: src/Components/Config/ConfigScreen.js (hunk 2 above)
Comment (seesemichaelj) [reply src/Components/Config/ConfigScreen.js]: I think this can't be done because the store is not available in the renderer process.

Comment (seesemichaelj) [reply src/Components/Config/ConfigScreen.js]: Nevermind about the above. I figured this out

File: src/Components/AppShell/AppShell.js (hunk 7 above)
[the remark this answers is not in the document]
Comment (seesemichaelj) [reply src/Components/AppShell/AppShell.js]: I will just go ahead and use showBugModal. We'll generalize it later if we need to.

File: src/Services/Settings.js (hunk 5 above)
Comment (seesemichaelj) [reply src/Services/Settings.js]: I'm going to address this by removing `validationErrors` from `initialSettings` but change the `state` from being `state.settings` to `state.config` which has a `settings` object as well as a `validationErrors` object. This keeps `validationErrors` as part of the state while not mixing it in with the `SettingsService`

File: src/Elements/StyledSelect.js (hunk 3 above)
Comment (benjamincburns) [reply src/Elements/StyledSelect.js]: re enumerating in the renderer process vs the main process, the rule of thumb we should follow is to only do browser-compatible things in the renderer process. Since this code wouldn't run in a browser it should be moved.

File: src/main.js (hunk 6 above)
Comment (benjamincburns) [reply src/main.js]: Yeah, I'd err the other way, but I don't feel particularly strongly about it, so :+1: by me.

File: src/Components/Config/ConfigScreens/ServerScreen.js [hunk 10]
```diff
@@ -68,6 +72,8 @@ class ServerScreen extends Component {
     //   !ganachePortStatus.pid[0].name.toLowerCase().includes('ganache') &&
     //   !ganachePortStatus.pid[0].name.toLowerCase().includes('electron')
 
+    const networkInterfaces = os.networkInterfaces()
```
Comment (benjamincburns) [inline src/Components/Config/ConfigScreens/ServerScreen.js]: Yeah, this needs to live in the main process - interfaces should be passed in via IPC

File: src/chain/logging.js [hunk 11]
```diff
@@ -1,19 +1,19 @@
 var path = require("path")
 var fs = require("fs")
-var padStart = require("lodash.padstart")
+var _ = require("lodash")
```
Comment (benjamincburns) [inline src/chain/logging.js]: Why switch from the piece-wise version to the full one? It'd be better to add piece-wise modules than to pack the whole of lodash - it's pretty big, IIRC.

Comment (benjamincburns) [reply src/chain/logging.js]: ignore this and just focus on the network interface enumeration stuff, then we're :+1:

File: src/Init/Renderer/Network.js [hunk 12]
```diff
@@ -0,0 +1,9 @@
+import { ipcRenderer } from 'electron'
+
+import * as Network from '../../Actions/Network'
```
Comment (benjamincburns) [inline src/Init/Renderer/Network.js]: Generally it's best to avoid `import * as ...` or `import Network` type imports in favor of `import { setInterface } from ...` because the latter allows for much smaller builds due to tree shaking.

File: src/Kernel/ready.js [hunk 13]
```diff
@@ -1,14 +1,10 @@
...
-import * as Web3 from '../Actions/Web3'
 import * as Core from '../Actions/Core'
-import * as Accounts from '../Actions/Accounts'
-import * as Logs from '../Actions/Logs'
-import * as Config from '../Actions/Config'
-
-import * as ErrorHandler from './ErrorHandler'
 
 import { initAutoUpdates } from '../Init/Renderer/AutoUpdate'
+import { initCore } from '../Init/Renderer/Core'
```
Comment (benjamincburns) [inline src/Kernel/ready.js]: Since `ready.js` is the renderer initialization entrypoint (unless I'm mistaken) perhaps it should be moved to `src/Init/Renderer/index.js`?

Ideally the `Kernel` directory wouldn't have continued to exist after this commit.
