### PR TITLE
fix:make events display again

### LINKED ISSUE #1293: I cannot see any events on event page
PLATFORM: mac os
GANACHE VERSION: 2.0.1

When I run the official metacoin example, I cannot see any events on event page. But my colleague was okay, and I was pretty much the same as his environment, and I was very confused.

image
image

### PR DESCRIPTION
**Pull request by davidmurdoch**
Contract events weren't showing up for users of `truffle@1.0.17` and higher due to a commit that removed the event's signature from migrated contract abis: https://github.com/trufflesuite/truffle/pull/1949

This PR fixes this issue by creating the event signature locally if it isn't already supplied in the abi.

Fixes #1293

### CODE REVIEW

**Comment by gnidan** [comment]
@haltman-at (added you as reviewer here, if you get the chance, to verify that the encoding logic is sufficiently correct)

File: src/truffle-integration/projectsWatcher.js [hunk 1]
```diff
@@ -121,7 +122,15 @@ class ProjectsWatcher extends EventEmitter {
           this.subscribedTopics.indexOf(entry.signature) === -1
         );
       });
-      topics = topics.concat(abiEvents.map(event => event.signature));
+      topics = topics.concat(
+        abiEvents.map(abi => {
```
Comment (nicholasjpaterno) [inline src/truffle-integration/projectsWatcher.js]: LGTM!  Although maybe it's a little verbose?  Thoughts on a ternary or short-circuit eval?
