### PR TITLE
Fix/not linking truffle projects

### LINKED ISSUE #1078: Ganache UI not linking my truffle project
## Expected Behavior

Ganache should link my contracts from my truffle-config.js

## Current Behavior

The Contracts tab displays: "To see rich contract data compile the contracts within your Truffle Project". I have already compiled and even migrated my contracts so I suppose that there is something wrong. 

## Possible Solution

Maybe my truffle-config.js has something wrong? Here the file (removing mnemonic for security reasons):

const path = require("path");
var HDWalletProvider = require("truffle-hdwallet-provider");

var mnemonic = "CHANGE_ME"; //Not my real mnemonic

module.exports = {
  // See <http://truffleframework.com/docs/advanced/configuration>
  // to customize your Truffle configuration!
  contracts_build_directory: path.join(__dirname, "client/src/contracts"),
  networks: {
    development: {
      host: "localhost", //My ganache network
      port: 9545,
      network_id: "*" // Match any network id
    },
    ropsten: {
      provider: function() {
        return new HDWalletProvider(mnemonic, "https://ropsten.infura.io/<INFURA_Access_Token>")
      },
      network_id: 3
    }, 
    alastria: {
      host: "34.234.56.789",
      port: 22000,
      gasPrice: 0,
      network_id: "*" //1140
    },
  }
};

## Steps to Reproduce (for bugs)

Link a project with that truffle-config.js and the standard truffle project with migrations, contract, etc... folders.

## Context

Already provided

## Your Environment

MAC OS X

### PR DESCRIPTION
**Pull request by honestbonsai**
Fixes #1078 

This PR does the following:

1. Fixes `contracts_build_directory` needing to be a direct child of `build_directory` (which defaults to `./build`) to get a Truffle project to link.
1. Allows you to put your `contracts_build_directory` as deep as you want as a descendant of your Truffle project. (e.g. `path/to/project/a/b/c/d/contracts_build_directory`)
1. Allows you to put your `contracts_build_directory` outside of your Truffle project (i.e. not a descendant).

It does not do:

1. Handle the renaming of a contract in the directory. This seems like a current bug with Ganache. Currently in `develop` and this branch, if you rename a contract's file name, all other contracts in Ganache disappear. If you try to rename it back to the original name, nothing changes. I considered this out of scope, will open a new issue for this.
1. Subfolders of contract artifacts within `contracts_build_directory`. Didn't seem like it was in scope for this card. If enough people want it, then a new issue/feature request should be made.

FYI:

1. Does seem to be slightly slower than the current implementation, since I'm recursing through the chain of directories. My feeling is that most people will just have their `contracts_build_directory` inside their project anyways, so this shouldn't be too big of an issue, but if you think it is let me know.

### CODE REVIEW

File: src/truffle-integration/projectFsWatcher.js [hunk 1]
```diff
@@ -89,18 +99,19 @@ class ProjectFsWatcher extends EventEmitter {
           ) {
             this.startWatchingContracts();
           }
+
+          if (tail[0] && filename === path.basename(tail[0]))
```
Comment (seesemichaelj) [inline src/truffle-integration/projectFsWatcher.js]: Perhaps this and lines 97/98 (won't let met comment there) should not be using the basename function, and be more something like

`path.join(head, filename) === path.normalize(this.project.config.contracts_build_directory)`

I don't think it's an issue either way as `startWatchingContracts()` will check to see if the directory exists before watching. Food for thought

**Comment by honestbonsai** [comment]
Yup, tested with `truffle unbox drizzle` and it works out of the box (haha)

**Comment by jjperezaguinaga** [comment]
Just wanted to comment that I've tested this with `truffle unbox react` and it works as well. Finishing a course w/Solidity this weekend with it, talking about good timing!
